<?php

/**
* Copyright 2018 Ayuntamiento de Santiago de Compostela, Entidad Pública Empresarial Red.es
*
* This file is part of the "Open Data Portal of Santiago de Compostela", developed within the "Ciudades Abiertas" project.
*
* Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/software/page/eupl
*
* Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and limitations under the Licence.
*/

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function csc_collaborate_form_contact_message_colabora_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    
    $form['message']['widget'][0]['value']['#title'] = t('Description');
    if (\Drupal::currentUser()->isAnonymous()) {
        $form['name']['#title'] = t('Name and surname');
    }
    $form['mail']['#title'] = t('Email');

    if (! array_key_exists('subject', $form)) {
        $form['subject'] = array(
            '#type' => 'hidden',
            '#value' => t('New collaboration'),
        );
    }

    if (array_key_exists('actions', $form)) {
        $form['actions']['reset'] = array(
            '#type' => 'button',
            '#button_type' => 'reset',
            '#value' => t('Clean'),
            '#weight' => 12,
            '#validate' => array(),
            '#attributes' => array(
                  'onclick' => 'this.form.reset(); return false;',
                  'accesskey' => 'r',
                ),
            );
    }

}
  