<?php

/**
* Copyright 2018 Ayuntamiento de Santiago de Compostela, Entidad Pública Empresarial Red.es
*
* This file is part of the "Open Data Portal of Santiago de Compostela", developed within the "Ciudades Abiertas" project.
*
* Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/software/page/eupl
*
* Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and limitations under the Licence.
*/

include_once (DRUPAL_ROOT . "/modules/custom/csc_ckan/libraries/dge_ckan_php_client/DgeCkanClient.php");

/**
 * @return DgeCkanClient
 */
function csc_ckan_init_class() {
    global $conf;
    
    $ckanConfig = \Drupal::config('ckan.config');
    
    $library = class_exists('DgeCkanClient');
    
    if (! $library) {
        drupal_set_message(t('DGE CKAN PHP Client is not installed'), 'error');
    }
    $apiUrl = $ckanConfig->get('ckan_host');
    $apiKey = $ckanConfig->get('ckan_api_key');
    
    $ckan = new DgeCkanClient($apiUrl, $apiKey, $conf);
    
    return $ckan;
}